---
# tasks file for find_facts
- name: Gather facts for all packages
  ansible.builtin.package_facts:
    manager: auto
  register: full_package

- name: Dump all package info for troubleshooting
  ansible.builtin.debug:
    var: ansible_facts['packages']
    verbosity: 2

# - name: Show Package dictionary as list
#   ansible.builtin.debug:
#     msg: "{{ ansible_facts['packages'] | map('extract', packages) | flatten | list  | first 10}} "
#     verbosity: 2
- name: Search Packages for named packages
  ansible.builtin.debug:
    msg: "{{ ansible_facts['packages'] | json_query(item) }}"
  loop: "{{ named_packages }}"

- name: Create Dictionary using named packages
  ansible.builtin.set_fact:
    found_packages: >-
      {{
        found_packages | default([]) +
        [{
           item:  ansible_facts['packages'] | json_query(item)
        }]
      }}
  loop: "{{ named_packages }}"

- name: Confirm Dictionary has content
  ansible.builtin.debug:
    var: found_packages
    verbosity: 2

# - name: Use the created fact
#   ansible.builtin.debug:
#     msg: |
#       Package name: {{ item.name }}
#       Version: {{ item.version }}
#       Release: {{ item.release }}
#       Source: {{ item.source }}
#   loop: "{{ found_packages }}"

- name: Create Report
  ansible.builtin.template:
    src: templates/template.system-report.json.j2
    owner: root
    mode: '0644'
    dest: /root/report
